### ISSUE TITLE
I tried out this footprint

### ISSUE THREAD

**Issue by jdart** [nilsolofsson/gateron_ks-27_footprint#1]
Thanks for sharing this footprint. I used it in a pcb manufactured by jlc and they appear to have manufactured it properly to spec. The switches I got from aliexpress have a 4.9mm, uh, circle extrusion, contrary to the specs dimensions of 4.8mm so they don't fit. I guess the spec isn't accurate. Do you have any switches with different measurements?

**Comment by nil-ski** [comment]
Huh weird. I made this footprint before I received my switches. And after I also realized that the switches don't necessarily follow the spec with the tht-pins. I had a version that I forgot to commit, which has oversized and round through-holes similar to the cherry-MX footprints to have some lee-way with variations of the tht-pins.

I don't have access to my switches nor a caliper atm to measure, but from what I can tell they were made according to spec. With a 4.8mm extrusion in the bottom.

I guess it wouldn't hurt to do the same with the center stem as I've done with the tht-pins to allow some variation in production processes and whatnot.

I'm going to order a board this week from JLC so if you want you can wait until I have received that to verify that it is working with my switches.

The switches I've got are from [nuphy directly](https://nuphy.com/collections/shop/products/gateron-low-profile-switches)

**Comment by Na-Cly** [comment]
Did you get to test the footprint? Looking to design a board with these.

**Comment by nil-ski** [comment]
@Na-Cly I haven't received my boards yet. Going by the tracking number, I guess they'll arrive sometime mid/late next week.

**Comment by Na-Cly** [comment]
Thanks. Keep us posted.

**Comment by nil-ski** [comment]
@jdart @Na-Cly so I've got my boards and tested my switches in them. They seem to be working great, click just in and sit really snug. The only thing is that the tht's could use a tad bigger solder pad to make it easier to solder them 🤔![image](https://user-images.githubusercontent.com/5212320/173636727-a0cb7aef-8464-4dee-b57f-f7153f2c30fe.jpeg)
![image](https://user-images.githubusercontent.com/5212320/173636742-cb211c91-1834-440f-85d8-2444e9b67dc4.jpeg)
